---
title: Lifestone Church
timezone: UTC
collections:
  sermons:
    title: Sermons
    output: true
    permalink: "/resources/sermons/:title/"
  redirects:
    title: Redirects
    output: true
    permalink: "/:path/"
    layout: redirect
defaults:
- scope:
    path: ''
    type: redirects
  values:
    layout: redirect
- scope:
    path: ''
    type: sermons
  values:
    layout: sermon
    categories:
    - sermons
baseurl: 
url: http://www.lifestonechurch.net
description: A Bible-based church in Herriman, Utah.
markdown: kramdown
managerName: Adam Harris
managerEmail: adam@mountainview-webdesign.com
organizationName: Lifestone Church
squareLogo: assets/images/logo2.jpg
podcastSubtitle: Messages from Sunday morning worship at Lifestone Church
permalink: "/:categories/:title/"
google_analytics_code: UA-44899328-1
